### ISSUE TITLE
no need for an 'install npm' step

### ISSUE THREAD

**Issue by paulzikopoulos** [IBM/cognitive-social-crm#36]
The steps tell you to install NPM but I think it's installed as part of node.js -- perhaps we can make the comment in brackets on that step

**Comment by stevemart** [comment]
@paulzikopoulos great suggestion, there's no need to make it seem like the two are separate since as you said they come together -- https://www.npmjs.com/get-npm -- i'll see if i can clean up the language.

<img width="582" alt="screen shot 2018-03-23 at 9 07 53 pm" src="https://user-images.githubusercontent.com/4118756/37858659-631afe1e-2ede-11e8-96b4-a60e2f8c6d87.png">
